// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (id, original_url, short_code, created_at)
VALUES ($1, $2, $3, $4)
RETURNING short_code
`

type CreateUrlParams struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   sql.NullTime
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUrl,
		arg.ID,
		arg.OriginalUrl,
		arg.ShortCode,
		arg.CreatedAt,
	)
	var short_code string
	err := row.Scan(&short_code)
	return short_code, err
}

const getUrlByOriginalUrl = `-- name: GetUrlByOriginalUrl :one
SELECT id, original_url, short_code, created_at FROM urls WHERE original_url = $1
`

func (q *Queries) GetUrlByOriginalUrl(ctx context.Context, originalUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrlByOriginalUrl, originalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const getUrlByShortCode = `-- name: GetUrlByShortCode :one
SELECT id, original_url, short_code, created_at FROM urls WHERE short_code = $1
`

func (q *Queries) GetUrlByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrlByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}
